/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Background.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Model/Background.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plus024.geometry}
        material={materials["Material.046"]}
        position={[-6.179, -9.326, 7.467]}
        rotation={[3.087, 0.346, -0.024]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus023.geometry}
        material={materials["Material.046"]}
        position={[-10.228, -12.011, 5.46]}
        rotation={[-3.012, -0.177, 0.104]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus022.geometry}
        material={materials["Material.046"]}
        position={[-1.601, -10.181, 0.988]}
        rotation={[-3.061, -0.272, 0.092]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus021.geometry}
        material={materials["Material.046"]}
        position={[3.134, -12.577, -3.853]}
        rotation={[3.036, 0.27, 0.051]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus020.geometry}
        material={materials["Material.046"]}
        position={[-5.107, -9.444, 3.964]}
        rotation={[3.025, -0.51, -0.057]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus019.geometry}
        material={materials["Material.046"]}
        position={[-0.246, -3.75, -3.32]}
        rotation={[-3.057, 0.134, -0.04]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus018.geometry}
        material={materials["Material.046"]}
        position={[14.185, -11.3, -2.645]}
        rotation={[-3.092, -0.67, -0.026]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus017.geometry}
        material={materials["Material.046"]}
        position={[6.871, -9.465, -4.359]}
        rotation={[3.032, -0.522, -0.042]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus016.geometry}
        material={materials["Material.046"]}
        position={[-5.013, -9.954, -1.424]}
        rotation={[-3.118, 0.394, 0.016]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus015.geometry}
        material={materials["Material.046"]}
        position={[7.915, -9.489, 3.255]}
        rotation={[-3.027, -0.139, 0.046]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus014.geometry}
        material={materials["Material.046"]}
        position={[-4.358, -9.985, 0.823]}
        rotation={[-3.114, 0.546, 0.057]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus013.geometry}
        material={materials["Material.046"]}
        position={[13.017, -11.695, 5.732]}
        rotation={[3.041, -0.389, -0.027]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Plus012.geometry}
        material={materials["Material.046"]}
        position={[6.528, -5.238, 3.13]}
        rotation={[3.041, -0.389, -0.027]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus011.geometry}
        material={materials["Material.046"]}
        position={[-4.353, -4.252, 0.302]}
        rotation={[-3.114, 0.546, 0.057]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus010.geometry}
        material={materials["Material.046"]}
        position={[3.587, -3.966, 1.703]}
        rotation={[-3.027, -0.139, 0.046]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus009.geometry}
        material={materials["Material.046"]}
        position={[-1.036, -4.234, -0.994]}
        rotation={[-3.118, 0.394, 0.016]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus008.geometry}
        material={materials["Material.046"]}
        position={[2.986, -3.953, -2.686]}
        rotation={[3.032, -0.522, -0.042]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus007.geometry}
        material={materials["Material.046"]}
        position={[7.201, -5.01, -1.698]}
        rotation={[-3.092, -0.67, -0.026]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus006.geometry}
        material={materials["Material.046"]}
        position={[-3.918, -3.94, 2.112]}
        rotation={[3.025, -0.51, -0.057]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus005.geometry}
        material={materials["Material.046"]}
        position={[0.831, -5.746, -2.394]}
        rotation={[3.036, 0.27, 0.051]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus004.geometry}
        material={materials["Material.046"]}
        position={[-1.898, -4.365, 0.396]}
        rotation={[-3.061, -0.272, 0.092]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus003.geometry}
        material={materials["Material.046"]}
        position={[-6.87, -5.42, 2.974]}
        rotation={[-3.012, -0.177, 0.104]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus002.geometry}
        material={materials["Material.046"]}
        position={[-4.537, -3.872, 4.131]}
        rotation={[3.087, 0.346, -0.024]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Plus.geometry}
        material={materials["Material.046"]}
        position={[1.264, -9.114, -5.459]}
        rotation={[-3.057, 0.134, -0.04]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus026.geometry}
        material={materials["Material.004"]}
        position={[-5.307, -4.273, -2.739]}
        rotation={[-3.011, 0.254, -0.098]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus025.geometry}
        material={materials["Material.004"]}
        position={[2.436, -4.757, -2.209]}
        rotation={[-3.049, -0.597, 0.091]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus024.geometry}
        material={materials["Material.004"]}
        position={[-13.903, -11.674, -0.25]}
        rotation={[-3.077, 0.015, -0.061]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus023.geometry}
        material={materials["Material.004"]}
        position={[-0.782, -11.104, -1.186]}
        rotation={[-3.055, 0.452, -0.106]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus022.geometry}
        material={materials["Material.004"]}
        position={[3.981, -12.414, -4.139]}
        rotation={[3.067, 0.516, 0.07]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus021.geometry}
        material={materials["Material.004"]}
        position={[-8.739, -11.516, -5.543]}
        rotation={[-3.117, 0.492, -0.006]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus020.geometry}
        material={materials["Material.004"]}
        position={[5.159, -9.639, -1.207]}
        rotation={[3.077, -0.246, -0.075]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus019.geometry}
        material={materials["Material.004"]}
        position={[-0.162, -4.874, 3.276]}
        rotation={[-3.117, -0.084, -0.008]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus018.geometry}
        material={materials["Material.004"]}
        position={[12.709, -10.914, -4.094]}
        rotation={[3.121, 0.225, -0.04]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus017.geometry}
        material={materials["Material.004"]}
        position={[-9.765, -12.743, -0.923]}
        rotation={[-3.141, 0.182, 0.029]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus016.geometry}
        material={materials["Material.004"]}
        position={[-5.361, -10.957, -3.033]}
        rotation={[-2.965, -0.521, 0.144]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus015.geometry}
        material={materials["Material.004"]}
        position={[2.403, -12.322, -3.159]}
        rotation={[-3.017, 0.077, -0.085]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus014.geometry}
        material={materials["Material.004"]}
        position={[-0.425, -10.66, 5.367]}
        rotation={[3.076, 0.089, 0.017]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus013.geometry}
        material={materials["Material.004"]}
        position={[1.41, -11.064, 5.983]}
        rotation={[-3.117, -0.084, -0.008]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus012.geometry}
        material={materials["Material.004"]}
        position={[5.917, -10.862, -3.532]}
        rotation={[-3.049, -0.597, 0.091]}
        scale={0.042}
      />
      <mesh
        geometry={nodes.Minus011.geometry}
        material={materials["Material.004"]}
        position={[-1.22, -4.641, 2.921]}
        rotation={[3.076, 0.089, 0.017]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus010.geometry}
        material={materials["Material.004"]}
        position={[0.41, -5.599, -1.994]}
        rotation={[-3.017, 0.077, -0.085]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus009.geometry}
        material={materials["Material.004"]}
        position={[-4.065, -4.812, -1.921]}
        rotation={[-2.965, -0.521, 0.144]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus008.geometry}
        material={materials["Material.004"]}
        position={[-6.604, -5.842, -0.705]}
        rotation={[-3.141, 0.182, 0.029]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus007.geometry}
        material={materials["Material.004"]}
        position={[6.35, -4.788, -2.533]}
        rotation={[3.121, 0.225, -0.04]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus006.geometry}
        material={materials["Material.004"]}
        position={[1.998, -4.052, -0.869]}
        rotation={[3.077, -0.246, -0.075]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus005.geometry}
        material={materials["Material.004"]}
        position={[-6.012, -5.135, -3.368]}
        rotation={[-3.117, 0.492, -0.006]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus004.geometry}
        material={materials["Material.004"]}
        position={[1.32, -5.652, -2.559]}
        rotation={[3.067, 0.516, 0.07]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus003.geometry}
        material={materials["Material.004"]}
        position={[-1.426, -4.897, -0.857]}
        rotation={[-3.055, 0.452, -0.106]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus002.geometry}
        material={materials["Material.004"]}
        position={[-8.988, -5.226, -0.317]}
        rotation={[-3.077, 0.015, -0.061]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Minus.geometry}
        material={materials["Material.004"]}
        position={[-7.515, -10.022, -4.451]}
        rotation={[-3.011, 0.254, -0.098]}
        scale={0.042}
      />
    </group>
  );
}

useGLTF.preload("/Model/Background.glb");
